# Generated by Django 2.2.5 on 2019-09-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distritoID', models.CharField(max_length=6)),
                ('province', models.CharField(max_length=50)),
                ('canton', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('grafico', models.ImageField(upload_to='')),
                ('mapa', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=50)),
                ('banda', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('antes', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_code', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=6)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hectarea', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Event')),
            ],
        ),
    ]
