# Generated by Django 2.2.5 on 2019-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mapa',
            field=models.ImageField(upload_to='mapa/'),
        ),
        migrations.AlterField(
            model_name='satimage',
            name='image',
            field=models.ImageField(upload_to='satimages'),
        ),
    ]
